<?php

namespace Database\Seeders;

use App\Models\Author;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AuthorSeeder extends Seeder
{
    public function run(): void
    {
        $authors = [
            'George Orwell',
            'Aldous Huxley',
            'J.R.R. Tolkien',
            'Isaac Asimov',
            'Arthur C. Clarke',
            'Philip K. Dick',
            'Ray Bradbury',
            'H.G. Wells',
            'Mary Shelley',
            'Bram Stoker',
            'Agatha Christie',
            'Arthur Conan Doyle',
            'Edgar Allan Poe',
            'Stephen King',
            'Dean Koontz',
            'Jane Austen',
            'Charlotte Brontë',
            'Emily Brontë',
            'Charles Dickens',
            'Mark Twain',
            'Ernest Hemingway',
            'F. Scott Fitzgerald',
            'William Shakespeare',
            'J.K. Rowling',
            'Neil Gaiman',
            'Terry Pratchett',
            'Brandon Sanderson',
            'Robert Jordan',
            'Frank Herbert',
            'Orson Scott Card',
            'Dan Brown',
            'John Grisham',
            'Tom Clancy',
            'Michael Crichton',
            'James Patterson',
            'C.S. Lewis',
            'Homer',
            'Virgil',
            'Dante Alighieri',
            'Miguel de Cervantes',
            'Leo Tolstoy',
            'Fyodor Dostoevsky',
            'Anton Chekhov',
            'Gabriel García Márquez',
            'Pablo Neruda',
            'Octavio Paz',
            'Haruki Murakami',
            'Kazuo Ishiguro',
            'Chinua Achebe',
            'George R.R. Martin',
            'Ursula K. Le Guin',
            'Stieg Larsson',
            'Gillian Flynn',
            'Paula Hawkins',
            'Walter Isaacson',
            'Siddhartha Mukherjee',
            'Paul Kalanithi',
            'Michelle Obama',
            'Stephen Covey',
            'James Clear',
            'Napoleon Hill',
            'Dale Carnegie',
            'Eckhart Tolle',
            'Richard Dawkins',
            'Carl Sagan',
            'Charles Darwin',
            'Rachel Carson',
            'Robert C. Martin',
            'David Thomas',
            'Thomas H. Cormen',
            'Steve McConnell',
            'Harold Abelson',
            'Stuart Russell',
            'Ian Goodfellow',
            'James Kurose',
            'Abraham Silberschatz',
            'James Stewart',
            'David C. Lay',
            'Kenneth Rosen',
            'Richard Rusczyk',
            'Joseph Blitzstein',
            'Marcus Aurelius',
            'Plato',
            'Aristotle',
            'Friedrich Nietzsche',
            'Jean-Paul Sartre',
            'Daniel Kahneman',
            'Viktor Frankl',
            'Charles Duhigg',
            'Robert Cialdini',
            'Malcolm Gladwell',
            'E.H. Gombrich',
            'John Berger',
            'Robert Henri',
            'Alex Ross',
            'Karen Chung',
            'T.S. Eliot',
            'Walt Whitman',
            'Bruce Chatwin',
            'Elizabeth Gilbert',
            'Julia Child',
            'Samin Nosrat',
            'Irma Rombauer',
            'Andre Agassi',
            'Michael Lewis',
            'Adam Smith',
            'Steven Levitt',
            'Thomas Piketty',
            'Paulo Freire',
            'John Holt',
            'Ken Robinson',
            'J.E. Gordon',
            'Henry Petroski',
            'Robert D. Putnam',
            'Niccolò Machiavelli',
            'Thomas Hobbes',
            'Alan Moore',
            'Frank Miller',
            'Art Spiegelman',
            'Raymond Chandler',
            'Robert Ludlum',
            'Diana Gabaldon',
            'Nicholas Sparks',
            'Jojo Moyes',
            'William Peter Blatty',
            'Yuval Noah Harari',
            'Jared Diamond',
            'Barbara W. Tuchman',
            'Mary Beard',
            'Nelson Mandela',
            'J.D. Salinger',
            'Neal Stephenson',
            'Scott Lynch',
            'Patrick Rothfuss',
            'Robin Hobb',
            'Terry Goodkind',
            'Joe Abercrombie',
            'Guy Gavriel Kay',
            'Mary Jane A. Intao',
        ];

        foreach ($authors as $author) {
            Author::firstOrCreate(
                ['author_name' => $author]
            );
        }
    }
}
