<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\Category;
use App\Models\Author;
use App\Models\Publisher;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::all()->keyBy('category_name');
        $authors = Author::all()->keyBy('author_name');
        $publishers = Publisher::all()->keyBy('publisher_name');

        $books = [
            // Fiction
            ['title' => '1984', 'category' => 'Fiction', 'author' => 'George Orwell', 'publisher' => 'Penguin Random House', 'isbn' => '978-0451524935', 'publication_year' => 1949, 'edition' => '1st', 'language' => 'English', 'pages' => 328, 'quantity' => 5, 'available_quantity' => 5, 'shelf_location' => 'A1-01', 'description' => 'A dystopian novel about totalitarianism and surveillance.'],
            ['title' => 'Brave New World', 'category' => 'Fiction', 'author' => 'Aldous Huxley', 'publisher' => 'HarperCollins', 'isbn' => '978-0060850524', 'publication_year' => 1932, 'edition' => '1st', 'language' => 'English', 'pages' => 288, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'A1-02', 'description' => 'A dystopian novel set in a futuristic World State.'],
            ['title' => 'Pride and Prejudice', 'category' => 'Fiction', 'author' => 'Jane Austen', 'publisher' => 'Penguin Random House', 'isbn' => '978-0141439518', 'publication_year' => 1813, 'edition' => 'Revised', 'language' => 'English', 'pages' => 432, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'A1-03', 'description' => 'A romantic novel of manners.'],
            ['title' => 'The Great Gatsby', 'category' => 'Fiction', 'author' => 'F. Scott Fitzgerald', 'publisher' => 'Scribner', 'isbn' => '978-0743273565', 'publication_year' => 1925, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 180, 'quantity' => 6, 'available_quantity' => 6, 'shelf_location' => 'A1-04', 'description' => 'A novel about the American Dream in the Jazz Age.'],
            ['title' => 'To Kill a Mockingbird', 'category' => 'Fiction', 'author' => 'Harper Lee', 'publisher' => 'HarperCollins', 'isbn' => '978-0061120084', 'publication_year' => 1960, 'edition' => '50th Anniversary', 'language' => 'English', 'pages' => 336, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'A1-05', 'description' => 'A novel about racial injustice in the Deep South.'],
            ['title' => 'The Catcher in the Rye', 'category' => 'Fiction', 'author' => 'J.D. Salinger', 'publisher' => 'Little, Brown', 'isbn' => '978-0316769488', 'publication_year' => 1951, 'edition' => 'Back Bay', 'language' => 'English', 'pages' => 277, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'A1-06', 'description' => 'A story about teenage alienation and rebellion.'],

            // Science Fiction
            ['title' => 'Dune', 'category' => 'Science Fiction', 'author' => 'Frank Herbert', 'publisher' => 'Penguin Random House', 'isbn' => '978-0441172719', 'publication_year' => 1965, 'edition' => 'Revised', 'language' => 'English', 'pages' => 688, 'quantity' => 5, 'available_quantity' => 5, 'shelf_location' => 'B2-01', 'description' => 'An epic science fiction novel set on the desert planet Arrakis.'],
            ['title' => 'Foundation', 'category' => 'Science Fiction', 'author' => 'Isaac Asimov', 'publisher' => 'Bantam Books', 'isbn' => '978-0553293357', 'publication_year' => 1951, 'edition' => '1st', 'language' => 'English', 'pages' => 244, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'B2-02', 'description' => 'A psychohistorian works to preserve knowledge through the fall of the Galactic Empire.'],
            ['title' => 'Neuromancer', 'category' => 'Science Fiction', 'author' => 'William Gibson', 'publisher' => 'Ace Books', 'isbn' => '978-0441569595', 'publication_year' => 1984, 'edition' => '1st', 'language' => 'English', 'pages' => 271, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'B2-03', 'description' => 'A pioneering cyberpunk novel about hackers and artificial intelligence.'],
            ['title' => 'Snow Crash', 'category' => 'Science Fiction', 'author' => 'Neal Stephenson', 'publisher' => 'Bantam Books', 'isbn' => '978-0553380958', 'publication_year' => 1992, 'edition' => '1st', 'language' => 'English', 'pages' => 440, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'B2-04', 'description' => 'A satirical cyberpunk novel about a hacker in a virtual reality world.'],
            ['title' => 'The Left Hand of Darkness', 'category' => 'Science Fiction', 'author' => 'Ursula K. Le Guin', 'publisher' => 'Ace Books', 'isbn' => '978-0441478125', 'publication_year' => 1969, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 304, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'B2-05', 'description' => 'A human envoy navigates a planet where humans have no fixed gender.'],

            // Fantasy
            ['title' => 'The Hobbit', 'category' => 'Fantasy', 'author' => 'J.R.R. Tolkien', 'publisher' => 'Houghton Mifflin', 'isbn' => '978-0547928227', 'publication_year' => 1937, 'edition' => '75th Anniversary', 'language' => 'English', 'pages' => 310, 'quantity' => 6, 'available_quantity' => 6, 'shelf_location' => 'C3-01', 'description' => 'A hobbit embarks on an unexpected journey with dwarves.'],
            ['title' => 'The Lord of the Rings', 'category' => 'Fantasy', 'author' => 'J.R.R. Tolkien', 'publisher' => 'Houghton Mifflin', 'isbn' => '978-0618640157', 'publication_year' => 1954, 'edition' => '50th Anniversary', 'language' => 'English', 'pages' => 1178, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'C3-02', 'description' => 'A fellowship sets out to destroy the One Ring.'],
            ['title' => 'A Game of Thrones', 'category' => 'Fantasy', 'author' => 'George R.R. Martin', 'publisher' => 'Bantam Books', 'isbn' => '978-0553593716', 'publication_year' => 1996, 'edition' => '1st', 'language' => 'English', 'pages' => 835, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'C3-03', 'description' => 'Noble families vie for control of the Iron Throne.'],
            ['title' => 'The Name of the Wind', 'category' => 'Fantasy', 'author' => 'Patrick Rothfuss', 'publisher' => 'DAW Books', 'isbn' => '978-0756404741', 'publication_year' => 2007, 'edition' => '1st', 'language' => 'English', 'pages' => 662, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'C3-04', 'description' => 'The story of a legendary figure told by himself.'],
            ['title' => 'The Way of Kings', 'category' => 'Fantasy', 'author' => 'Brandon Sanderson', 'publisher' => 'Tor Books', 'isbn' => '978-0765326355', 'publication_year' => 2010, 'edition' => '1st', 'language' => 'English', 'pages' => 1007, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'C3-05', 'description' => 'The first book in the Stormlight Archive series.'],
            ['title' => 'The Lies of Locke Lamora', 'category' => 'Fantasy', 'author' => 'Scott Lynch', 'publisher' => 'Bantam Books', 'isbn' => '978-0553588981', 'publication_year' => 2006, 'edition' => '1st', 'language' => 'English', 'pages' => 499, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'C3-06', 'description' => 'A fantasy about a gang of con artists in a Venice-like city.'],

            // Mystery
            ['title' => 'The Murder of Roger Ackroyd', 'category' => 'Mystery', 'author' => 'Agatha Christie', 'publisher' => 'HarperCollins', 'isbn' => '978-0062693662', 'publication_year' => 1926, 'edition' => 'Revised', 'language' => 'English', 'pages' => 288, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'D4-01', 'description' => 'A classic whodunit featuring Hercule Poirot.'],
            ['title' => 'The Hound of the Baskervilles', 'category' => 'Mystery', 'author' => 'Arthur Conan Doyle', 'publisher' => 'Penguin Random House', 'isbn' => '978-0141183668', 'publication_year' => 1902, 'edition' => 'Revised', 'language' => 'English', 'pages' => 256, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'D4-02', 'description' => 'Sherlock Holmes investigates a supernatural hound.'],
            ['title' => 'The Big Sleep', 'category' => 'Mystery', 'author' => 'Raymond Chandler', 'publisher' => 'Vintage Books', 'isbn' => '978-0394758282', 'publication_year' => 1939, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 231, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'D4-03', 'description' => 'A hardboiled detective novel featuring Philip Marlowe.'],
            ['title' => 'Gone Girl', 'category' => 'Mystery', 'author' => 'Gillian Flynn', 'publisher' => 'Crown Publishing', 'isbn' => '978-0307588371', 'publication_year' => 2012, 'edition' => '1st', 'language' => 'English', 'pages' => 415, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'D4-04', 'description' => 'A psychological thriller about a missing wife.'],
            ['title' => 'The Girl with the Dragon Tattoo', 'category' => 'Mystery', 'author' => 'Stieg Larsson', 'publisher' => 'Knopf', 'isbn' => '978-0307454546', 'publication_year' => 2005, 'edition' => '1st', 'language' => 'English', 'pages' => 672, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'D4-05', 'description' => 'A journalist and hacker investigate a decades-old disappearance.'],

            // Thriller
            ['title' => 'The Da Vinci Code', 'category' => 'Thriller', 'author' => 'Dan Brown', 'publisher' => 'Doubleday', 'isbn' => '978-0307474278', 'publication_year' => 2003, 'edition' => 'Special Illustrated', 'language' => 'English', 'pages' => 597, 'quantity' => 5, 'available_quantity' => 5, 'shelf_location' => 'E5-01', 'description' => 'A symbologist uncovers a conspiracy hidden in art.'],
            ['title' => 'The Firm', 'category' => 'Thriller', 'author' => 'John Grisham', 'publisher' => 'Doubleday', 'isbn' => '978-0385416469', 'publication_year' => 1991, 'edition' => '1st', 'language' => 'English', 'pages' => 432, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'E5-02', 'description' => 'A young lawyer discovers his firm is a front for the mob.'],
            ['title' => 'The Bourne Identity', 'category' => 'Thriller', 'author' => 'Robert Ludlum', 'publisher' => 'Richard Marek Publishers', 'isbn' => '978-0553260113', 'publication_year' => 1980, 'edition' => '1st', 'language' => 'English', 'pages' => 512, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'E5-03', 'description' => 'An amnesiac assassin searches for his identity.'],
            ['title' => 'Patriot Games', 'category' => 'Thriller', 'author' => 'Tom Clancy', 'publisher' => 'Putnam', 'isbn' => '978-0425261569', 'publication_year' => 1987, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 528, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'E5-04', 'description' => 'Jack Ryan foils a terrorist attack.'],
            ['title' => 'The Girl on the Train', 'category' => 'Thriller', 'author' => 'Paula Hawkins', 'publisher' => 'Riverhead Books', 'isbn' => '978-1594633669', 'publication_year' => 2015, 'edition' => '1st', 'language' => 'English', 'pages' => 336, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'E5-05', 'description' => 'A commuter witnesses a shocking event from a train.'],

            // Romance
            ['title' => 'Jane Eyre', 'category' => 'Romance', 'author' => 'Charlotte Brontë', 'publisher' => 'Penguin Random House', 'isbn' => '978-0141441146', 'publication_year' => 1847, 'edition' => 'Revised', 'language' => 'English', 'pages' => 532, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'F6-01', 'description' => 'A governess falls in love with her mysterious employer.'],
            ['title' => 'Wuthering Heights', 'category' => 'Romance', 'author' => 'Emily Brontë', 'publisher' => 'Penguin Random House', 'isbn' => '978-0141439556', 'publication_year' => 1847, 'edition' => 'Revised', 'language' => 'English', 'pages' => 416, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'F6-02', 'description' => 'A passionate and tragic love story on the Yorkshire moors.'],
            ['title' => 'Outlander', 'category' => 'Romance', 'author' => 'Diana Gabaldon', 'publisher' => 'Delacorte Press', 'isbn' => '978-0440212560', 'publication_year' => 1991, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 850, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'F6-03', 'description' => 'A WWII nurse travels back in time to 18th-century Scotland.'],
            ['title' => 'The Notebook', 'category' => 'Romance', 'author' => 'Nicholas Sparks', 'publisher' => 'Grand Central Publishing', 'isbn' => '978-1455582877', 'publication_year' => 1996, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 228, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'F6-04', 'description' => 'A man reads to his wife from a notebook recounting their love story.'],
            ['title' => 'Me Before You', 'category' => 'Romance', 'author' => 'Jojo Moyes', 'publisher' => 'Penguin Random House', 'isbn' => '978-0143124542', 'publication_year' => 2012, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 369, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'F6-05', 'description' => 'A caregiver and her quadriplegic employer find love.'],

            // Horror
            ['title' => 'Frankenstein', 'category' => 'Horror', 'author' => 'Mary Shelley', 'publisher' => 'Penguin Random House', 'isbn' => '978-0141439477', 'publication_year' => 1818, 'edition' => 'Revised', 'language' => 'English', 'pages' => 280, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'G7-01', 'description' => 'A scientist creates a sentient creature with tragic consequences.'],
            ['title' => 'Dracula', 'category' => 'Horror', 'author' => 'Bram Stoker', 'publisher' => 'Penguin Random House', 'isbn' => '978-0141439846', 'publication_year' => 1897, 'edition' => 'Revised', 'language' => 'English', 'pages' => 418, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'G7-02', 'description' => 'Count Dracula moves from Transylvania to England.'],
            ['title' => 'The Shining', 'category' => 'Horror', 'author' => 'Stephen King', 'publisher' => 'Anchor Books', 'isbn' => '978-0307743657', 'publication_year' => 1977, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 688, 'quantity' => 5, 'available_quantity' => 5, 'shelf_location' => 'G7-03', 'description' => 'A family is snowed in at a haunted hotel.'],
            ['title' => 'It', 'category' => 'Horror', 'author' => 'Stephen King', 'publisher' => 'Scribner', 'isbn' => '978-1501142970', 'publication_year' => 1986, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 1139, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'G7-04', 'description' => 'Seven friends confront an evil entity in their hometown.'],
            ['title' => 'The Exorcist', 'category' => 'Horror', 'author' => 'William Peter Blatty', 'publisher' => 'HarperCollins', 'isbn' => '978-0060817221', 'publication_year' => 1971, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 340, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'G7-05', 'description' => 'A young girl is possessed by a demonic entity.'],

            // History
            ['title' => 'A Brief History of Time', 'category' => 'History', 'author' => 'Stephen Hawking', 'publisher' => 'Bantam Books', 'isbn' => '978-0553380163', 'publication_year' => 1988, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 256, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'H8-01', 'description' => 'A layman\'s guide to cosmology and the universe.'],
            ['title' => 'Sapiens', 'category' => 'History', 'author' => 'Yuval Noah Harari', 'publisher' => 'HarperCollins', 'isbn' => '978-0062316097', 'publication_year' => 2011, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 498, 'quantity' => 5, 'available_quantity' => 5, 'shelf_location' => 'H8-02', 'description' => 'A brief history of humankind from the Stone Age to the present.'],
            ['title' => 'Guns, Germs, and Steel', 'category' => 'History', 'author' => 'Jared Diamond', 'publisher' => 'W.W. Norton', 'isbn' => '978-0393354324', 'publication_year' => 1997, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 528, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'H8-03', 'description' => 'Why some civilizations conquered others.'],
            ['title' => 'The Guns of August', 'category' => 'History', 'author' => 'Barbara W. Tuchman', 'publisher' => 'Presidio Press', 'isbn' => '978-0345476098', 'publication_year' => 1962, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 544, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'H8-04', 'description' => 'A Pulitzer Prize-winning account of the outbreak of WWI.'],
            ['title' => 'SPQR', 'category' => 'History', 'author' => 'Mary Beard', 'publisher' => 'Liveright Publishing', 'isbn' => '978-0871404237', 'publication_year' => 2015, 'edition' => '1st', 'language' => 'English', 'pages' => 608, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'H8-05', 'description' => 'A sweeping history of ancient Rome.'],

            // Biography
            ['title' => 'The Diary of a Young Girl', 'category' => 'Biography', 'author' => 'Anne Frank', 'publisher' => 'Penguin Random House', 'isbn' => '978-0553296983', 'publication_year' => 1947, 'edition' => 'Revised', 'language' => 'English', 'pages' => 352, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'I9-01', 'description' => 'The diary of a Jewish girl hiding during WWII.'],
            ['title' => 'Long Walk to Freedom', 'category' => 'Biography', 'author' => 'Nelson Mandela', 'publisher' => 'Little, Brown', 'isbn' => '978-0316548182', 'publication_year' => 1994, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 656, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'I9-02', 'description' => 'The autobiography of Nelson Mandela.'],
            ['title' => 'Steve Jobs', 'category' => 'Biography', 'author' => 'Walter Isaacson', 'publisher' => 'Simon & Schuster', 'isbn' => '978-1451648539', 'publication_year' => 2011, 'edition' => '1st', 'language' => 'English', 'pages' => 656, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'I9-03', 'description' => 'The definitive biography of Steve Jobs.'],
            ['title' => 'Einstein: His Life and Universe', 'category' => 'Biography', 'author' => 'Walter Isaacson', 'publisher' => 'Simon & Schuster', 'isbn' => '978-0743264747', 'publication_year' => 2007, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 704, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'I9-04', 'description' => 'A comprehensive biography of Albert Einstein.'],
            ['title' => 'Becoming', 'category' => 'Biography', 'author' => 'Michelle Obama', 'publisher' => 'Crown Publishing', 'isbn' => '978-1524763138', 'publication_year' => 2018, 'edition' => '1st', 'language' => 'English', 'pages' => 448, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'I9-05', 'description' => 'The memoir of former First Lady Michelle Obama.'],

            // Self-Help
            ['title' => 'The 7 Habits of Highly Effective People', 'category' => 'Self-Help', 'author' => 'Stephen Covey', 'publisher' => 'Simon & Schuster', 'isbn' => '978-1451639612', 'publication_year' => 1989, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 432, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'J10-01', 'description' => 'A guide to personal and professional effectiveness.'],
            ['title' => 'Atomic Habits', 'category' => 'Self-Help', 'author' => 'James Clear', 'publisher' => 'Avery Publishing', 'isbn' => '978-0735211292', 'publication_year' => 2018, 'edition' => '1st', 'language' => 'English', 'pages' => 320, 'quantity' => 5, 'available_quantity' => 5, 'shelf_location' => 'J10-02', 'description' => 'Tiny changes that produce remarkable results.'],
            ['title' => 'Think and Grow Rich', 'category' => 'Self-Help', 'author' => 'Napoleon Hill', 'publisher' => 'Penguin Random House', 'isbn' => '978-1585424337', 'publication_year' => 1937, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 384, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'J10-03', 'description' => 'A classic guide to achieving wealth and success.'],
            ['title' => 'How to Win Friends and Influence People', 'category' => 'Self-Help', 'author' => 'Dale Carnegie', 'publisher' => 'Simon & Schuster', 'isbn' => '978-0671027032', 'publication_year' => 1936, 'edition' => 'Revised', 'language' => 'English', 'pages' => 304, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'J10-04', 'description' => 'Techniques for handling people and making friends.'],
            ['title' => 'The Power of Now', 'category' => 'Self-Help', 'author' => 'Eckhart Tolle', 'publisher' => 'New World Library', 'isbn' => '978-1577314806', 'publication_year' => 1997, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 236, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'J10-05', 'description' => 'A guide to spiritual enlightenment and living in the present.'],

            // Science
            ['title' => 'A Brief History of Time', 'category' => 'Science', 'author' => 'Stephen Hawking', 'publisher' => 'Bantam Books', 'isbn' => '978-0553380163', 'publication_year' => 1988, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 256, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'K11-01', 'description' => 'From the Big Bang to black holes.'],
            ['title' => 'The Selfish Gene', 'category' => 'Science', 'author' => 'Richard Dawkins', 'publisher' => 'Oxford University Press', 'isbn' => '978-0199291151', 'publication_year' => 1976, 'edition' => '30th Anniversary', 'language' => 'English', 'pages' => 360, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'K11-02', 'description' => 'A revolutionary look at evolution through gene-centered view.'],
            ['title' => 'Cosmos', 'category' => 'Science', 'author' => 'Carl Sagan', 'publisher' => 'Random House', 'isbn' => '978-0345539434', 'publication_year' => 1980, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 432, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'K11-03', 'description' => 'A journey through the universe with astronomer Carl Sagan.'],
            ['title' => 'The Origin of Species', 'category' => 'Science', 'author' => 'Charles Darwin', 'publisher' => 'Penguin Random House', 'isbn' => '978-0140439120', 'publication_year' => 1859, 'edition' => 'Revised', 'language' => 'English', 'pages' => 576, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'K11-04', 'description' => 'The foundational work on evolutionary biology.'],
            ['title' => 'Silent Spring', 'category' => 'Science', 'author' => 'Rachel Carson', 'publisher' => 'Houghton Mifflin', 'isbn' => '978-0618249060', 'publication_year' => 1962, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 400, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'K11-05', 'description' => 'A landmark book that launched the environmental movement.'],

            // Technology
            ['title' => 'Clean Code', 'category' => 'Technology', 'author' => 'Robert C. Martin', 'publisher' => 'Prentice Hall', 'isbn' => '978-0132350884', 'publication_year' => 2008, 'edition' => '1st', 'language' => 'English', 'pages' => 464, 'quantity' => 5, 'available_quantity' => 5, 'shelf_location' => 'L12-01', 'description' => 'A handbook of agile software craftsmanship.'],
            ['title' => 'The Pragmatic Programmer', 'category' => 'Technology', 'author' => 'David Thomas', 'publisher' => 'Addison-Wesley', 'isbn' => '978-0135957059', 'publication_year' => 2019, 'edition' => '20th Anniversary', 'language' => 'English', 'pages' => 352, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'L12-02', 'description' => 'Your journey to mastery in software development.'],
            ['title' => 'Design Patterns', 'category' => 'Technology', 'author' => 'Gang of Four', 'publisher' => 'Addison-Wesley', 'isbn' => '978-0201633610', 'publication_year' => 1994, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 416, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'L12-03', 'description' => 'Elements of reusable object-oriented software.'],
            ['title' => 'Introduction to Algorithms', 'category' => 'Technology', 'author' => 'Thomas H. Cormen', 'publisher' => 'MIT Press', 'isbn' => '978-0262033848', 'publication_year' => 2009, 'edition' => '3rd', 'language' => 'English', 'pages' => 1312, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'L12-04', 'description' => 'A comprehensive textbook on algorithms.'],
            ['title' => 'Code Complete', 'category' => 'Technology', 'author' => 'Steve McConnell', 'publisher' => 'Microsoft Press', 'isbn' => '978-0735619678', 'publication_year' => 2004, 'edition' => '2nd', 'language' => 'English', 'pages' => 960, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'L12-05', 'description' => 'A practical handbook of software construction.'],

            // Computer Science
            ['title' => 'Structure and Interpretation of Computer Programs', 'category' => 'Computer Science', 'author' => 'Harold Abelson', 'publisher' => 'MIT Press', 'isbn' => '978-0262510875', 'publication_year' => 1996, 'edition' => '2nd', 'language' => 'English', 'pages' => 657, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'M13-01', 'description' => 'A foundational textbook on computer science principles.'],
            ['title' => 'Artificial Intelligence: A Modern Approach', 'category' => 'Computer Science', 'author' => 'Stuart Russell', 'publisher' => 'Pearson Education', 'isbn' => '978-0134610993', 'publication_year' => 2020, 'edition' => '4th', 'language' => 'English', 'pages' => 1136, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'M13-02', 'description' => 'The standard textbook on artificial intelligence.'],
            ['title' => 'Deep Learning', 'category' => 'Computer Science', 'author' => 'Ian Goodfellow', 'publisher' => 'MIT Press', 'isbn' => '978-0262035613', 'publication_year' => 2016, 'edition' => '1st', 'language' => 'English', 'pages' => 800, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'M13-03', 'description' => 'A comprehensive introduction to deep learning.'],
            ['title' => 'Computer Networking', 'category' => 'Computer Science', 'author' => 'James Kurose', 'publisher' => 'Pearson Education', 'isbn' => '978-0133594140', 'publication_year' => 2016, 'edition' => '7th', 'language' => 'English', 'pages' => 864, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'M13-04', 'description' => 'A top-down approach to computer networking.'],
            ['title' => 'Operating System Concepts', 'category' => 'Computer Science', 'author' => 'Abraham Silberschatz', 'publisher' => 'Wiley', 'isbn' => '978-1119456339', 'publication_year' => 2018, 'edition' => '10th', 'language' => 'English', 'pages' => 976, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'M13-05', 'description' => 'The definitive guide to operating systems.'],

            // Mathematics
            ['title' => 'Calculus', 'category' => 'Mathematics', 'author' => 'James Stewart', 'publisher' => 'Cengage Learning', 'isbn' => '978-1285740621', 'publication_year' => 2015, 'edition' => '8th', 'language' => 'English', 'pages' => 1392, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'N14-01', 'description' => 'A comprehensive calculus textbook.'],
            ['title' => 'Linear Algebra and Its Applications', 'category' => 'Mathematics', 'author' => 'David C. Lay', 'publisher' => 'Pearson Education', 'isbn' => '978-0321982384', 'publication_year' => 2015, 'edition' => '5th', 'language' => 'English', 'pages' => 576, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'N14-02', 'description' => 'An introduction to linear algebra.'],
            ['title' => 'Discrete Mathematics and Its Applications', 'category' => 'Mathematics', 'author' => 'Kenneth Rosen', 'publisher' => 'McGraw-Hill Education', 'isbn' => '978-0073383095', 'publication_year' => 2018, 'edition' => '8th', 'language' => 'English', 'pages' => 1072, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'N14-03', 'description' => 'A comprehensive guide to discrete mathematics.'],
            ['title' => 'The Art of Problem Solving', 'category' => 'Mathematics', 'author' => 'Richard Rusczyk', 'publisher' => 'AoPS Inc', 'isbn' => '978-0977304561', 'publication_year' => 2006, 'edition' => '1st', 'language' => 'English', 'pages' => 288, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'N14-04', 'description' => 'A problem-solving approach to mathematics.'],
            ['title' => 'Introduction to Probability', 'category' => 'Mathematics', 'author' => 'Joseph Blitzstein', 'publisher' => 'Chapman and Hall', 'isbn' => '978-1138369917', 'publication_year' => 2014, 'edition' => '1st', 'language' => 'English', 'pages' => 592, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'N14-05', 'description' => 'An introduction to probability theory and its applications.'],

            // Philosophy
            ['title' => 'Meditations', 'category' => 'Philosophy', 'author' => 'Marcus Aurelius', 'publisher' => 'Penguin Random House', 'isbn' => '978-0140449334', 'publication_year' => 180, 'edition' => 'Revised', 'language' => 'English', 'pages' => 256, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'O15-01', 'description' => 'Personal writings of the Roman Emperor Marcus Aurelius.'],
            ['title' => 'The Republic', 'category' => 'Philosophy', 'author' => 'Plato', 'publisher' => 'Penguin Random House', 'isbn' => '978-0140455113', 'publication_year' => -380, 'edition' => 'Revised', 'language' => 'English', 'pages' => 416, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'O15-02', 'description' => 'Plato\'s masterwork on justice and the ideal state.'],
            ['title' => 'Nicomachean Ethics', 'category' => 'Philosophy', 'author' => 'Aristotle', 'publisher' => 'Penguin Random House', 'isbn' => '978-0140459530', 'publication_year' => -340, 'edition' => 'Revised', 'language' => 'English', 'pages' => 400, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'O15-03', 'description' => 'Aristotle\'s seminal work on ethics and virtue.'],
            ['title' => 'Beyond Good and Evil', 'category' => 'Philosophy', 'author' => 'Friedrich Nietzsche', 'publisher' => 'Penguin Random House', 'isbn' => '978-0140449235', 'publication_year' => 1886, 'edition' => 'Revised', 'language' => 'English', 'pages' => 240, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'O15-04', 'description' => 'Nietzsche\'s critique of traditional morality.'],
            ['title' => 'Being and Nothingness', 'category' => 'Philosophy', 'author' => 'Jean-Paul Sartre', 'publisher' => 'Simon & Schuster', 'isbn' => '978-0671867805', 'publication_year' => 1943, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 835, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'O15-05', 'description' => 'Sartre\'s existentialist masterpiece.'],

            // Psychology
            ['title' => 'Thinking, Fast and Slow', 'category' => 'Psychology', 'author' => 'Daniel Kahneman', 'publisher' => 'Farrar, Straus and Giroux', 'isbn' => '978-0374533557', 'publication_year' => 2011, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 512, 'quantity' => 4, 'available_quantity' => 4, 'shelf_location' => 'P16-01', 'description' => 'Nobel laureate Daniel Kahneman explains how we think.'],
            ['title' => 'Man\'s Search for Meaning', 'category' => 'Psychology', 'author' => 'Viktor Frankl', 'publisher' => 'Beacon Press', 'isbn' => '978-0807014271', 'publication_year' => 1946, 'edition' => 'Revised', 'language' => 'English', 'pages' => 200, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'P16-02', 'description' => 'A psychiatrist\'s memoir of surviving the Holocaust.'],
            ['title' => 'The Power of Habit', 'category' => 'Psychology', 'author' => 'Charles Duhigg', 'publisher' => 'Random House', 'isbn' => '978-0812981605', 'publication_year' => 2012, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 400, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'P16-03', 'description' => 'Why we do what we do in life and business.'],
            ['title' => 'Influence', 'category' => 'Psychology', 'author' => 'Robert Cialdini', 'publisher' => 'HarperBusiness', 'isbn' => '978-0061241895', 'publication_year' => 2006, 'edition' => 'Revised', 'language' => 'English', 'pages' => 592, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'P16-04', 'description' => 'The psychology of persuasion.'],
            ['title' => 'Blink', 'category' => 'Psychology', 'author' => 'Malcolm Gladwell', 'publisher' => 'Back Bay Books', 'isbn' => '978-0316013324', 'publication_year' => 2005, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 304, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'P16-05', 'description' => 'The power of thinking without thinking.'],

            // Art
            ['title' => 'The Story of Art', 'category' => 'Art', 'author' => 'E.H. Gombrich', 'publisher' => 'Phaidon Press', 'isbn' => '978-0714832470', 'publication_year' => 1950, 'edition' => '16th Revised', 'language' => 'English', 'pages' => 688, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'Q17-01', 'description' => 'A comprehensive history of art from ancient times to the modern era.'],
            ['title' => 'Ways of Seeing', 'category' => 'Art', 'author' => 'John Berger', 'publisher' => 'Penguin Random House', 'isbn' => '978-0140135152', 'publication_year' => 1972, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 176, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'Q17-02', 'description' => 'A groundbreaking critique of visual culture.'],
            ['title' => 'The Art Spirit', 'category' => 'Art', 'author' => 'Robert Henri', 'publisher' => 'Basic Books', 'isbn' => '978-0465007172', 'publication_year' => 1923, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 320, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'Q17-03', 'description' => 'Notes on art and creativity.'],

            // Music
            ['title' => 'The Rest Is Noise', 'category' => 'Music', 'author' => 'Alex Ross', 'publisher' => 'Farrar, Straus and Giroux', 'isbn' => '978-0312427719', 'publication_year' => 2007, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 640, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'R18-01', 'description' => 'A history of 20th-century music.'],
            ['title' => 'How to Read Music', 'category' => 'Music', 'author' => 'Karen Chung', 'publisher' => 'Schirmer Books', 'isbn' => '978-1423430152', 'publication_year' => 2004, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 96, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'R18-02', 'description' => 'A simple guide to reading musical notation.'],

            // Poetry
            ['title' => 'The Waste Land', 'category' => 'Poetry', 'author' => 'T.S. Eliot', 'publisher' => 'Penguin Random House', 'isbn' => '978-0141182517', 'publication_year' => 1922, 'edition' => 'Revised', 'language' => 'English', 'pages' => 128, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'S19-01', 'description' => 'A landmark modernist poem.'],
            ['title' => 'Leaves of Grass', 'category' => 'Poetry', 'author' => 'Walt Whitman', 'publisher' => 'Penguin Random House', 'isbn' => '978-0140422006', 'publication_year' => 1855, 'edition' => 'Revised', 'language' => 'English', 'pages' => 152, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'S19-02', 'description' => 'A collection of poems celebrating nature and the human spirit.'],

            // Drama
            ['title' => 'Hamlet', 'category' => 'Drama', 'author' => 'William Shakespeare', 'publisher' => 'Simon & Schuster', 'isbn' => '978-0743477123', 'publication_year' => 1603, 'edition' => 'Revised', 'language' => 'English', 'pages' => 342, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'T20-01', 'description' => 'Shakespeare\'s tragedy about the Prince of Denmark.'],
            ['title' => 'Romeo and Juliet', 'category' => 'Drama', 'author' => 'William Shakespeare', 'publisher' => 'Simon & Schuster', 'isbn' => '978-0743477116', 'publication_year' => 1597, 'edition' => 'Revised', 'language' => 'English', 'pages' => 304, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'T20-02', 'description' => 'The tragic love story of two young lovers.'],
            ['title' => 'Macbeth', 'category' => 'Drama', 'author' => 'William Shakespeare', 'publisher' => 'Simon & Schuster', 'isbn' => '978-0743477109', 'publication_year' => 1606, 'edition' => 'Revised', 'language' => 'English', 'pages' => 272, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'T20-03', 'description' => 'A tragedy about ambition, power, and guilt.'],

            // Travel
            ['title' => 'In Patagonia', 'category' => 'Travel', 'author' => 'Bruce Chatwin', 'publisher' => 'Penguin Random House', 'isbn' => '978-0142437190', 'publication_year' => 1977, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 240, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'U21-01', 'description' => 'A travelogue exploring the remote region of Patagonia.'],
            ['title' => 'Eat, Pray, Love', 'category' => 'Travel', 'author' => 'Elizabeth Gilbert', 'publisher' => 'Penguin Random House', 'isbn' => '978-0143038412', 'publication_year' => 2006, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 352, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'U21-02', 'description' => 'A woman travels to Italy, India, and Bali in search of meaning.'],

            // Cooking
            ['title' => 'Mastering the Art of French Cooking', 'category' => 'Cooking', 'author' => 'Julia Child', 'publisher' => 'Knopf', 'isbn' => '978-0375413407', 'publication_year' => 1961, 'edition' => 'Revised', 'language' => 'English', 'pages' => 752, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'V22-01', 'description' => 'A classic French cookbook for home cooks.'],
            ['title' => 'Salt, Fat, Acid, Heat', 'category' => 'Cooking', 'author' => 'Samin Nosrat', 'publisher' => 'Simon & Schuster', 'isbn' => '978-1476759700', 'publication_year' => 2017, 'edition' => '1st', 'language' => 'English', 'pages' => 464, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'V22-02', 'description' => 'A revolutionary approach to cooking.'],
            ['title' => 'The Joy of Cooking', 'category' => 'Cooking', 'author' => 'Irma Rombauer', 'publisher' => 'Scribner', 'isbn' => '978-1501169714', 'publication_year' => 1931, 'edition' => 'Revised', 'language' => 'English', 'pages' => 1152, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'V22-03', 'description' => 'The all-purpose cookbook.'],

            // Sports
            ['title' => 'Open', 'category' => 'Sports', 'author' => 'Andre Agassi', 'publisher' => 'Knopf', 'isbn' => '978-0307388381', 'publication_year' => 2009, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 416, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'W23-01', 'description' => 'The autobiography of tennis legend Andre Agassi.'],
            ['title' => 'Moneyball', 'category' => 'Sports', 'author' => 'Michael Lewis', 'publisher' => 'W.W. Norton', 'isbn' => '978-0393338391', 'publication_year' => 2003, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 304, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'W23-02', 'description' => 'How Billy Beane used analytics to transform baseball.'],
            ['title' => 'The Blind Side', 'category' => 'Sports', 'author' => 'Michael Lewis', 'publisher' => 'W.W. Norton', 'isbn' => '978-0393337592', 'publication_year' => 2006, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 336, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'W23-03', 'description' => 'The evolution of American football and the left tackle position.'],

            // Economics
            ['title' => 'The Wealth of Nations', 'category' => 'Economics', 'author' => 'Adam Smith', 'publisher' => 'Penguin Random House', 'isbn' => '978-0140436114', 'publication_year' => 1776, 'edition' => 'Revised', 'language' => 'English', 'pages' => 1248, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'X24-01', 'description' => 'The foundational work on modern economics.'],
            ['title' => 'Freakonomics', 'category' => 'Economics', 'author' => 'Steven Levitt', 'publisher' => 'HarperCollins', 'isbn' => '978-0060731335', 'publication_year' => 2005, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 336, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'X24-02', 'description' => 'A rogue economist explores the hidden side of everything.'],
            ['title' => 'Capital in the Twenty-First Century', 'category' => 'Economics', 'author' => 'Thomas Piketty', 'publisher' => 'Harvard University Press', 'isbn' => '978-0674979857', 'publication_year' => 2014, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 696, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'X24-03', 'description' => 'An analysis of wealth inequality over centuries.'],

            // Education
            ['title' => 'Pedagogy of the Oppressed', 'category' => 'Education', 'author' => 'Paulo Freire', 'publisher' => 'Bloomsbury Academic', 'isbn' => '978-1501314134', 'publication_year' => 1968, 'edition' => 'Revised', 'language' => 'English', 'pages' => 192, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'Y25-01', 'description' => 'A critical approach to education and liberation.'],
            ['title' => 'How Children Learn', 'category' => 'Education', 'author' => 'John Holt', 'publisher' => 'Da Capo Press', 'isbn' => '978-0201484025', 'publication_year' => 1967, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 320, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'Y25-02', 'description' => 'A classic on how children naturally learn.'],
            ['title' => 'The Element', 'category' => 'Education', 'author' => 'Ken Robinson', 'publisher' => 'Viking', 'isbn' => '978-0670023179', 'publication_year' => 2009, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 288, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'Y25-03', 'description' => 'How finding your passion changes everything.'],

            // Medicine
            ['title' => 'The Emperor of All Maladies', 'category' => 'Medicine', 'author' => 'Siddhartha Mukherjee', 'publisher' => 'Scribner', 'isbn' => '978-1439170915', 'publication_year' => 2010, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 592, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'Z26-01', 'description' => 'A biography of cancer from ancient times to modern treatments.'],
            ['title' => 'When Breath Becomes Air', 'category' => 'Medicine', 'author' => 'Paul Kalanithi', 'publisher' => 'Random House', 'isbn' => '978-0812988406', 'publication_year' => 2016, 'edition' => '1st', 'language' => 'English', 'pages' => 228, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'Z26-02', 'description' => 'A neurosurgeon confronts mortality.'],
            ['title' => 'The Gene', 'category' => 'Medicine', 'author' => 'Siddhartha Mukherjee', 'publisher' => 'Scribner', 'isbn' => '978-1476733524', 'publication_year' => 2016, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 608, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'Z26-03', 'description' => 'An intimate history of the gene and its impact on identity.'],

            // Engineering
            ['title' => 'Structures', 'category' => 'Engineering', 'author' => 'J.E. Gordon', 'publisher' => 'University of Chicago Press', 'isbn' => '978-0226285546', 'publication_year' => 1978, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 256, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'AA27-01', 'description' => 'Why things don\'t fall down - an accessible look at structural engineering.'],
            ['title' => 'The Innovators', 'category' => 'Engineering', 'author' => 'Walter Isaacson', 'publisher' => 'Simon & Schuster', 'isbn' => '978-1476708690', 'publication_year' => 2014, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 560, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'AA27-02', 'description' => 'The story of the digital revolution and its genius hackers.'],
            ['title' => 'To Engineer Is Human', 'category' => 'Engineering', 'author' => 'Henry Petroski', 'publisher' => 'Vintage Books', 'isbn' => '978-0679734163', 'publication_year' => 1985, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 288, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'AA27-03', 'description' => 'The role of failure in successful design.'],

            // Sociology
            ['title' => 'The Tipping Point', 'category' => 'Sociology', 'author' => 'Malcolm Gladwell', 'publisher' => 'Back Bay Books', 'isbn' => '978-0316346627', 'publication_year' => 2000, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 304, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'BB28-01', 'description' => 'How little things can make a big difference.'],
            ['title' => 'Outliers', 'category' => 'Sociology', 'author' => 'Malcolm Gladwell', 'publisher' => 'Back Bay Books', 'isbn' => '978-0316017932', 'publication_year' => 2008, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 336, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'BB28-02', 'description' => 'The story of success and what makes high-achievers different.'],
            ['title' => 'Bowling Alone', 'category' => 'Sociology', 'author' => 'Robert D. Putnam', 'publisher' => 'Simon & Schuster', 'isbn' => '978-0743203043', 'publication_year' => 2000, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 544, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'BB28-03', 'description' => 'The collapse and revival of American community.'],

            // Political Science
            ['title' => 'The Prince', 'category' => 'Political Science', 'author' => 'Niccolò Machiavelli', 'publisher' => 'Penguin Random House', 'isbn' => '978-0140449159', 'publication_year' => 1532, 'edition' => 'Revised', 'language' => 'English', 'pages' => 176, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'CC29-01', 'description' => 'Machiavelli\'s classic treatise on political power.'],
            ['title' => 'Leviathan', 'category' => 'Political Science', 'author' => 'Thomas Hobbes', 'publisher' => 'Penguin Random House', 'isbn' => '978-0140431957', 'publication_year' => 1651, 'edition' => 'Revised', 'language' => 'English', 'pages' => 576, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'CC29-02', 'description' => 'Hobbes\' foundational work on social contract theory.'],
            ['title' => 'The Republic', 'category' => 'Political Science', 'author' => 'Plato', 'publisher' => 'Penguin Random House', 'isbn' => '978-0140455113', 'publication_year' => -375, 'edition' => 'Revised', 'language' => 'English', 'pages' => 416, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'CC29-03', 'description' => 'Plato\'s dialogue on justice and the ideal state.'],

            // Comics
            ['title' => 'Watchmen', 'category' => 'Comics', 'author' => 'Alan Moore', 'publisher' => 'DC Comics', 'isbn' => '978-1401245252', 'publication_year' => 1986, 'edition' => 'Deluxe', 'language' => 'English', 'pages' => 416, 'quantity' => 3, 'available_quantity' => 3, 'shelf_location' => 'DD30-01', 'description' => 'A groundbreaking graphic novel about retired superheroes.'],
            ['title' => 'Batman: The Dark Knight Returns', 'category' => 'Comics', 'author' => 'Frank Miller', 'publisher' => 'DC Comics', 'isbn' => '978-1563893421', 'publication_year' => 1986, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 224, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'DD30-02', 'description' => 'An aging Batman returns to fight crime.'],
            ['title' => 'Maus', 'category' => 'Comics', 'author' => 'Art Spiegelman', 'publisher' => 'Pantheon Books', 'isbn' => '978-0679406417', 'publication_year' => 1986, 'edition' => 'Reprint', 'language' => 'English', 'pages' => 296, 'quantity' => 2, 'available_quantity' => 2, 'shelf_location' => 'DD30-03', 'description' => 'A Pulitzer Prize-winning graphic novel about the Holocaust.'],
        ];

        foreach ($books as $bookData) {
            $category = $categories->get($bookData['category']);
            $author = $authors->get($bookData['author']);
            $publisher = $publishers->get($bookData['publisher']);

            if ($category && $author && $publisher) {
                Book::firstOrCreate(
                    ['isbn' => $bookData['isbn']],
                    [
                        'title' => $bookData['title'],
                        'category_id' => $category->id,
                        'author_id' => $author->id,
                        'publisher_id' => $publisher->id,
                        'publication_year' => $bookData['publication_year'],
                        'edition' => $bookData['edition'],
                        'language' => $bookData['language'],
                        'pages' => $bookData['pages'],
                        'quantity' => $bookData['quantity'],
                        'available_quantity' => $bookData['available_quantity'],
                        'shelf_location' => $bookData['shelf_location'],
                        'description' => $bookData['description'],
                        'status' => 'Available',
                    ]
                );
            }
        }
    }
}
